### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Co2Noss** [nate8282/GuildNoteUpdater#1]
3x GuildNoteUpdater/GuildNoteUpdater.lua:120: attempt to index field 'enabledCharacters' (a nil value)
[string "@GuildNoteUpdater/GuildNoteUpdater.lua"]:120: in function `UpdateGuildNote'
[string "@GuildNoteUpdater/GuildNoteUpdater.lua"]:73: in function <GuildNoteUpdater/GuildNoteUpdater.lua:71>

Locals:
self = Frame {
 previousNote = ""
 hasUpdated = false
}
checkForChanges = nil
characterName = "Hammerlocks"
(*temporary) = nil
(*temporary) = "Hammerlocks"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'enabledCharacters' (a nil value)"

3x GuildNoteUpdater/GuildNoteUpdater.lua:47: attempt to index field 'mainOrAlt' (a nil value)
[string "@GuildNoteUpdater/GuildNoteUpdater.lua"]:47: in function `InitializeSettings'
[string "@GuildNoteUpdater/GuildNoteUpdater.lua"]:63: in function `OnEvent'
[string "@GuildNoteUpdater/GuildNoteUpdater.lua"]:113: in function <GuildNoteUpdater/GuildNoteUpdater.lua:112>

Locals:
self = Frame {
 previousNote = ""
 hasUpdated = false
}
characterName = "Hammerlocks"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'mainOrAlt' (a nil value)"

10x GuildNoteUpdater/GuildNoteUpdater.lua:101: attempt to index global 'GuildNoteUpdaterUI' (a nil value)
[string "@GuildNoteUpdater/GuildNoteUpdater.lua"]:101: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5479: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5425>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5131: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5130>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5167: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5163>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>
[string "=[C]"]: ?

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'GuildNoteUpdaterUI' (a nil value)"

**Comment by Co2Noss** [comment]
Fixed in 1.3. Looks like professions were added too which is nice. Don't really like having dashes in the note like that though. would rather it be 596 Destruction Tail Enc Alt

**Comment by nate8282** [comment]
Thanks for the input. I appreciate that. I'll consider changing the format when i get the time
